### ISSUE TITLE
[Feature] Allow matching rules for alert/record name

### ISSUE THREAD

**Issue by GMartinez-Sisti** [cloudflare/pint#1020]
Hi, I would like to be able to specify rules to match alert/record names also. Currently we can only match labels and annotations but it would be good to be able to provide rules for alert names to keep some consistency.

A direct example of this would be to prevent alert names from having dashes or underscores, to match a maximum size or even require a prefix/suffix matcher.

I'm happy to give it a try if you think it would be a good contribution to the project.

**Comment by prymitive** [comment]
Added in #1048
