### ISSUE TITLE
RFE: Allow query/series to be disabled for only some series, or special-case ALERTS{}

### ISSUE THREAD

**Issue by siebenmann** [cloudflare/pint#112]
We have some alert rules designed to detect large-scale issues and avoid flooding us with smaller alerts. As part of the alert rules, these alerts count active alerts using ALERTS{alertstate="firing"}. Normally we have no firing alerts, so when I run a pint check of our alert rules I get a query/series warning for this. I can disable this warning for the entire alert rule with `# pint disable query/series`, but the alert rule contains other series that I would like pint to check to make sure they exist. It would be nice if pint would either allow you to disable only a specific series in a rule instead of all of them, or alternately if it had a special case for the ALERTS series.

(Or perhaps there's already a way to do this.)

**Comment by prymitive** [comment]
The tricky bit is that there's very little that's "definitely wrong" in Prometheus world, a lot depends on intentions and given setup. That's the main reason checks like this simply print out results and let a human interpret these.
For now the only "definitely not incorrect" solution is to manually disable warnings for some selectors.

It's not currently possible but I've added support for it via #113 which will be in v0.6.5.
With that release you'll be able to add `# pint disable query/series(ALERTS)` or `# pint disable query/series(ALERTS{alertstate="firing"})` comments that should disable checks for individual series.

**Comment by prymitive** [comment]
FYI ALERTS is handled better starting with v0.15 - https://cloudflare.github.io/pint/changelog.html#v0150
