### ISSUE TITLE
[Feature Request] Support using pint as library / embed into other programs

### ISSUE THREAD

**Issue by timo-reymann** [cloudflare/pint#1124]
Currently pint is only usable as a command line application, without even a minimal API exposed.

This makes it de-facto impossible to embed it into other go applications. Which is exactly the use case I have.

What do you think about at least offering sth like

```golang
package other_tool

import (
  "github.com/cloudflare/pint/cli"
  "os"
)

func main() {
  cli.Run(os.Args)
}
```

Where `cli.Run` is basically the same done in [cmd/pint/main.go](https://github.com/cloudflare/pint/blob/e801589a43c62e0073909a20413cc8d99beee8b6/cmd/pint/main.go#L135-L136)

This would enable embedding pint into other applications for easier integration and distribution.

**Comment by prymitive** [comment]
pint is a tool we developed to improve health of our internal Prometheus rule deployment. The goal was to have a cli tool and a daemon, we don't have a use case for embedding and so it's a non-goal.
