### ISSUE TITLE
Unable to disable some checks globally

### ISSUE THREAD

**Issue by pznamensky** [cloudflare/pint#118]
Hi,
I've noticed that at some point in time `template {}` check was enabled by default.
Nevertheless, we'd like to disable `alerts/template` check for all our alerting rules.
It looks like the only way to do it is to edit each rule and add `pint disable` comment which is not very useful for our volume.
Is it possible to add the ability to ignore some checks globally?

**Comment by prymitive** [comment]
This should be doable right now, although undocumented it seems, by adding:

```
checks {
  disabled = ["alerts/template"]
}
```

to your config file.

**Comment by pznamensky** [comment]
Indeed, I didn't find this in docs, but it works!
@prymitive, thank you!
