### ISSUE TITLE
Watch mod - add files name 

### ISSUE THREAD

**Issue by Veres72** [cloudflare/pint#170]
Hello. 
Watch mod is very useful but it's a little bit hard to indicate where exactly pint found a problem. Could you add file name where pint found a problem as lablel of pint_problem metrics? 
Now we take an alert name from metrics and grep alerts via all files in the directory which pint is checking. 
It could be cool to add in metrics label with file name. 
Eg. 
Current metrics 
`pint_problem{kind="alerting",name="TestAlert",problem="query using prometheus completed without any results for test_metrics",reporter="query/series",severity="warning"} 1`
Possible metrics with file name 
`pint_problem{kind="alerting",name="TestAlert",problem="query using prometheus completed without any results for test_metrics",reporter="query/series",severity="warning",file="testrule1,yaml"} 1`

**Comment by prymitive** [comment]
Watch mode is still being actively worked on, so it's not 100% there yet.
I've raised a PR to add `filename` label, thanks!
