### ISSUE TITLE
Example of using the relaxed parser

### ISSUE THREAD

**Issue by RyanW8** [cloudflare/pint#252]
Hey guys, I'm having a play with pint to try and incorporate it into our pipelines. Currently prometheus alerting & recording rules are in an ArgoCD Application resource nested under `.spec.source.helm.values.serverFiles.alerts` and `.spec.source.helm.values.serverFiles.rules`. Annoyingly `.spec.source.helm.values` is a multi-line string using the block style indicator (`|`). 

This means we have to extract the values into a new yaml file for pint to parse it as a yaml rather than a string. 

I'm wondering if there's a way to get pint to parse the multi-line string as YAML?

**Comment by prymitive** [comment]
Please try `v0.19.0`, it includes #256 and should parse your files correctly - https://cloudflare.github.io/pint/changelog.html#v0190
