### ISSUE TITLE
Run Pint against Thanos Query

### ISSUE THREAD

**Issue by nicolastakashi** [cloudflare/pint#260]
It would be nice to enable the usage of Pint against the Thanos Query so that we can leverage the excellent pint functionalities when we're using a distributed monitoring solution or using components such as Thanos Ruler.

I was looking into the code, and I guess that the only thing that is avoiding it, is because pint is getting the Prometheus config for the Prometheus API `/api/v1/status/config`.

I've tested by running pint on my local machine and after to comment the code that is going through the config API, could be nice if we have the possibility to provide those values by config and skip the API in this case

**Comment by prymitive** [comment]
The only check that uses config is [promql/rate](https://cloudflare.github.io/pint/checks/promql/rate.html), so if you disable it all should work, see https://cloudflare.github.io/pint/checks/promql/rate.html#how-to-disable-it
