### ISSUE TITLE
Only show bug/warning level problems

### ISSUE THREAD

**Issue by kovaxur** [cloudflare/pint#268]
Hi,
Is it possible to only make it print bug and warning messages?

For example, I have the following ouput:
level=info msg="Problems found" Bug=8 Information=228 Warning=4

But I would only be interested in the bugs and warnings.

Thanks

**Comment by prymitive** [comment]
Could you provide more details? What command are you running? What are those information reports?

There are some checks that only generate information level reports, like `alerts/count`, in which case you can just disable that check - https://cloudflare.github.io/pint/checks/alerts/count.html#how-to-disable-it

**Comment by kovaxur** [comment]
Hi,
Yes, I just over complicated it, it's enough to just disable those checks, thanks!
