### ISSUE TITLE
Intelligent base branch detection

### ISSUE THREAD

**Issue by GiedriusS** [cloudflare/pint#27]
We ran into a problem where people's branches become stale after someone merges some new changes into the base branch and then `pint` tries to report problems on issues that they haven't introduced themselves. As far as I know, GitHub does not have a base branch ref of a pull request: https://github.com/isaacs/github/issues/757.

Thus, I propose adding an option such as `pick_base_branch` to the `ci` block. If set to true then when `pint` runs it should point to a merged ref, and `pint` should automatically detect the base branch from that.  

Either `pick_base_branch` should be set or `baseBranch` - not both. @prymitive what do you think? If it makes sense then I could implement this. It would solve some pain points for us.

**Comment by prymitive** [comment]
How are you running pint? Is it via actions or some other way?

For actions there seem to be base ref in the context - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

**Comment by GiedriusS** [comment]
Via Jenkins. FWIW I have worked around this problem by having `baseBranch = "$baseBranchPlaceholder"` and:

```
COMMON_ANCESTOR = sh(script: "git merge-base origin/${env.GIT_BRANCH} origin/${env.CHANGE_TARGET}", returnStdout: true).trim()
sh "sed -i 's/\$baseBranchPlaceholder/${COMMON_ANCESTOR}/g' .pint.hcl"
```

I guess the ergonomics could be improved here however that's a different issue altogether so I'll close this. Thanks for your response & time! `pint` is great (:
