### ISSUE TITLE
Confusing or incorrect message about an ALERTS based alert rule

### ISSUE THREAD

**Issue by siebenmann** [cloudflare/pint#326]
Recent versions of pint are giving us the following message:
```
etc/prometheus/cslab/alerts/largescale.yaml:62: ALERTS{alertname!="DownNvidiaAgent",alertstate="firing",cshost=~"(<...>).*",cstype="host"} metric is generated by alerts and found alerting rule named "DownNvidiaAgent" (promql/series)
 62 |     expr: max_over_time(sum(max(label_replace(ALERTS{alertname!="DownNvidiaAgent",alertstate="firing",cstype="host",cshost=~"(<...>).*"}, "cshost", "$1", "cshost", "(.*).cs.toronto.edu")) by (cshost))[20m:]) >= 10 or
```
The debug message associated with this rule in the source is 'Metric is provided by alerting rule', in internal/checks/promql_series.go.

I don't understand what this message is trying to tell us. Yes, the metric is generated by alerts and yes we have an alert by the name of this, so we have not typo'd the alertname here. But that seems to be everything working as intended, not something that should produce any sort of message. If this message has to be produced, it would be good to provide a way to suppress just it (or just informational messages), rather than having to lose all promql/series messages about ALERTS (since we might make a typo there that we'd miss by suppressing all such messages).

**Comment by prymitive** [comment]
That's gone in v0.28.2
