### ISSUE TITLE
RFE: provide a way to suppress just the new  'consider using one of the humanize template functions' alerts/template message

### ISSUE THREAD

**Issue by siebenmann** [cloudflare/pint#327]
The very latest version of pint contains a new warning to the effect that:
```
using the value of [query] inside this annotation might be hard to read, consider using one of humanize template functions to make it more human friendly (alerts/template)
```
This is currently listed as a Warning and can't be specifically suppressed as far as I can see; all you can suppress is the entire set of alerts/template checks. I think that this is potentially useful but it can also misfire, and I would like to be able to suppress just it, without missing any other template problems.

Possibly this should also be a lower severity message than the current warning level.

**Comment by prymitive** [comment]
[v0.28.2](https://cloudflare.github.io/pint/changelog.html#v0282) add `--min-severity` flag to `pint lint` and it defaults to `warning`. That should help
