### ISSUE TITLE
What is the difference between pint and promtool ?

### ISSUE THREAD

**Issue by chenlujjj** [cloudflare/pint#33]
promtool has `check rules` option:
```
  check rules <rule-files>...
    Check if the rule files are valid or not.
```

So what is the difference between pint and promtool ?

**Comment by prymitive** [comment]
promtool will only do syntax checks, so it will warn you if the rule is written incorrectly.
pint does all sorts of checks (that you configure) on the rule itself, including if the metrics used are present in Prometheus 

tl;dr promtool will tell you if the rule won’t work at all, pint can tell you that + if the rule doesn’t do what you want it to do

https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/#syntax-checking-rules

**Comment by chenlujjj** [comment]
Thank you for the reply!
