### ISSUE TITLE
Alert using predict_linear() causes parse error

### ISSUE THREAD

**Issue by BenoitKnecht** [cloudflare/pint#372]
I'm getting the following error with `pint` 0.29.3 (revision: 7ab7c95d71df937fc76745ed7818f0873197f3eb):

```
alerts.yml:212-215: prometheus "example" at https://prometheus.example.com failed with: bad_data: invalid parameter "query": 1:45: parse error: trailing commas not allowed in function call args (promql/vector_matching)
 212 |         expr: |
 213 |           predict_linear(ceph_pool_max_avail[2d], 3600 * 24 * 5) *
 214 |           on(pool_id) group_left(name) ceph_pool_metadata
 215 |           < 0
```

However, that expression is correct, but `pint` seems to be running it without the `3600 * 24 * 5` part. In fact, it trips on it elsewhere in the code, where you can clearly see the `predict_linear()` function missing its second argument:

```
level=error msg="Query returned an error" error="invalid parameter \"query\": 1:45: parse error: trailing commas not allowed in function call args" query="count(predict_linear(ceph_pool_max_avail[2d], ) * on (pool_id) group_left (name) ceph_pool_metadata)" uri=https://prometheus.example.com
```

**Comment by prymitive** [comment]
This is likely because some checks will strip queries from all conditions just to see if they would return anything, and that might be doing something silly with those arguments.
Should be easy to fix
