### ISSUE TITLE
promql/series: Ignore missing series based on some condition

### ISSUE THREAD

**Issue by BenoitKnecht** [cloudflare/pint#374]
Here's the use case. We have a test environment with a single Alertmanager (clustering disabled), while our production environments have a pair of Alertmanager with clustering disabled.

One of our alerts is

```
alertmanager_cluster_failed_peers > 0
```

which works fine in both environments, because the metric doesn't exist when clustering is disabled (hence the alert never fires), and it correctly detects failures in our production environments.

But `pint` is not happy about the missing series, and I don't want to ignore the issue entirely. What I would like to do is either

1. Be able to ignore metrics on a specific Prometheus server, e.g.
    ```hcl
    prometheus "test" {
        uri = "https://test.example.com"
        timeout = "1m"
    }
    prometheus "prod" {
        uri = "https://prod.example.com"
        timeout = "1m"
    }
    check "promql/series" {
        prometheus "test" {
            ignoreMetrics = [
                "alertmanager_cluster_failed_peers",
            ]
        }
    }
    ```
    or something like that, hopefully you get the idea.
2. Ignore a missing metric based on the value returned by another query (in this case if `alertmanager_cluster_enabled == 0`).

But perhaps I missed a way to achieve what I'm trying to do that is already supported?

**Comment by prymitive** [comment]
> Be able to ignore metrics on a specific Prometheus server, e.g. 

You can do this already: https://cloudflare.github.io/pint/checks/promql/series.html#how-to-disable-it

**Comment by BenoitKnecht** [comment]
That's awesome, even better than what I had in mind! Sorry for not finding it myself, and thanks for this great tool!
