### ISSUE TITLE
packaging consistency for github releases

### ISSUE THREAD

**Issue by visheyra** [cloudflare/pint#393]
Hi there,

While automating the download and execution of pint across various devices (mainly apple m1 arm64 and x86_64 linux) I noticed a difference in packaging.

When one download the darwin arm64 release the tarball contains the arm64 arch both in the name of the archive and within the archive

link:`https://github.com/cloudflare/pint/releases/download/v0.30.2/pint-0.30.2-darwin-arm64.tar.gz`
```shell
❯ ls pint-0.30.2-darwin-arm64
LICENSE			README.md		pint-darwin-arm64
```

However, for the linux release, the arch in the binary name has been changed

link: `https://github.com/cloudflare/pint/releases/download/v0.30.2/pint-0.30.2-linux-x86_64.tar.gz`
content:
```shell
❯ ls pint-0.30.2-linux-x86_64
LICENSE			README.md		pint-linux-amd64
```

While it is not a huge problem I see 2 reasons why this should be fixed:

* when working with uname the expected architecture output on linux 64 bits  is `x86_64` not `amd64`
* it's a pain to write cross platform scripts due to that

I would be happy to help you tackle / PR this issue LMK

**Comment by prymitive** [comment]
#412 should fix this for the next release
