### ISSUE TITLE
support authenticated endpoints?

### ISSUE THREAD

**Issue by anarcat** [cloudflare/pint#409]
Is there a way to specify HTTP auth credentials to probe a remote prometheus server? ours is protected by a password, and it seems it fails, even with a URL like <https://user:pass@example.com/>.

**Comment by prymitive** [comment]
`https://user:pass@example.com` should work, that error are you getting when using that?

**Comment by anarcat** [comment]
it looks like that *does* work, not sure what i was doing wrong. sorry for the noise!
