### ISSUE TITLE
Lint stand alone query

### ISSUE THREAD

**Issue by nicolastakashi** [cloudflare/pint#43]
Have a possibility the lint only an expression, so that this tool could be used to lint stand-alone queries used on dashboards.

**Comment by prymitive** [comment]
What problems would you expect to find by linting a query? Can you give some example?

**Comment by nicolastakashi** [comment]
Hi @prymitive thanks for replying to me.
If we are able to only lint a query, we can take advantage of infra as code implementation, where the teams just need to input the alert query and the rest of the template is always created by a tool such as Ansible.

**Comment by prymitive** [comment]
Maybe I wasn't clear enough: pint lints alerting/recording rules, there's usually very little it can detect in the query itself. So the question is: you pass a query to pint, what do you expect to get as a result? What kind of feedback are you looking for here? Can you give me example query and example problem that should be detected in that query?
