### ISSUE TITLE
Re-Review post issues

### ISSUE THREAD

**Issue by rk-p2p** [cloudflare/pint#478]
Hi!
Got an error after new commits after the first PR review.
Steps to reproduce:
1. Create a PR with some errors in the prometheus targets file;
2. Get your first PR review from pint;
3. Change something else and push commits to PR;
4. You will receive this error.
```level=fatal msg="Execution completed with error(s)" error="submitting reports: creating review: POST https://api.github.com/repos/xxx/yyy/pulls/95/reviews: 422 Unprocessable Entity [{Resource: Field: Code: Message:Pull request review thread line must be part of the diff, Pull request review thread start line must be part of the same hunk as the line., and Pull request review thread diff hunk can't be blank}]"```

**Comment by prymitive** [comment]
I see that current GH integration can also create duplicated comments and would probably make sense to move it to use checks API - https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28
I'll try to look into that when I have some time

**Comment by prymitive** [comment]
This is fixed in the next release - #486
