### ISSUE TITLE
Add excludes in config lelvel, not only alerts yaml. 

### ISSUE THREAD

**Issue by Veres72** [cloudflare/pint#48]
Hello. 
Could you add ignoring alerts by name or regexp via config file? 
It will be nice for cases when there is no way to declare excludes in alerts declaration. 
E.g we want to lint alerts in multitenancy cluster and send a notification to teams, which have alerts without time series. Teams are deploying their alerts as promerheusRules object and there is not possible to keep comments.

**Comment by prymitive** [comment]
Added `ignore` blocks to `match` - #81.
Plus there's a `name` field on `match` and `ignore` to allow matching by `alert` and `record` fields on prometheus rules.
Example:

```
rule {
    ignore {
        name = "Ignore .+"
    }
    ...
}
```

Would ignore this alert:

```
- alert: Ignore This Alert
  expr: sum(foo) > 0
```
