### ISSUE TITLE
getting checks skipped

### ISSUE THREAD

**Issue by ravibhooshan** [cloudflare/pint#491]
Hi, 
I am testing pint ci and getting below message
myuser@pint % ./pint ci ~/Desktop/e1_cass_alert_rules.yml
level=info msg="Loading configuration file" path=.pint.hcl
level=info msg="Running from base branch, skipping checks" branch=main

Below is my config file:
This same file gives proper result , if I run with "lint".
Please let me know what I am doing wrong here.
`repository {
  github {
    baseuri    = "https://github.myname.com/"
    uploaduri  = "https://github.myname.com/"
    timeout    = "1m"
    owner      = "git@github.myname.com"
    repo       = "pg-rulefiles"
  }
}

ci {
  include    =  ["template/e1_prom_alert_rules.yml"]
  maxCommits = 50
  baseBranch = "main"
}

prometheus "dev" {
  uri     = "https://saharapromxy-dev.aexp.com"
  timeout = "30s"

}

rule {
  # This block will apply to all alerting rules.
  match {
    kind = "alerting"
    
	}
 cost{
   severity = "bug"
  maxSeries = 100
	}
#reject url vaule in label's value
reject "https?://.+" {
    label_keys = true
    label_values = true
  }
#reject any spave in Annotation & label name

reject ".* +.*" {
	annotation_keys = true
	label_keys = true
}

#checking labels

label "ticketing" {
    severity = "bug"
    required = true
}

label "impacted_ci" {
    severity = "bug"
    required = true
}

#checking Annotations
annotation "summary" {
    severity = "bug"
    required = true
  }

}
`

**Comment by prymitive** [comment]
`pint ci` is for running checks on modified rules from a branch, you're running from `main` so there's nothing to check.
