### ISSUE TITLE
promql/series: expose lookback as config variable

### ISSUE THREAD

**Issue by fbs** [cloudflare/pint#493]
I have a thanos setup where prometheus only has 2 days worth of data. The older data has to be accessed through a thanos endpoint and alert rules over longer time periods have to be be placed on the ruler.

The lookback period is currently hard coded to 7 days but as there is no data there is no point in going back that far. The amount of queries it has to do to cover 7 days, multiple testcases and multiple series per rule also do add up, and it might cause incorrect output as well.

I'd like to see the lookback period exposed as config option, e.g.

```
check "promql/series" {
  lookbackPeriod = "6h"
}
```

How do you feel about this?

I already [implemented](https://github.com/fbs/pint/commit/bb97df6fe187a36af364261848229d4518acb89a) something but the contribution guide recommended to open an issue before opening a PR :)

**Comment by prymitive** [comment]
Fixed via #498

**Comment by fbs** [comment]
Thanks!
