### ISSUE TITLE
alerts/count - doesnt show alert estimation result

### ISSUE THREAD

**Issue by AlbusLumos** [cloudflare/pint#522]
I've enabled the alerts/count check by adding prometheus and rule block 

prometheus "prod" {
  uri     = "https://xxx"
  timeout = "60s"
}

rule {
  alerts {
    range      = "1h"
    step       = "1m"
    resolve    = "5m"
  }
}

but the lint result seems not showing how many alerts would trigger.
level=info msg="Loading configuration file" path=.pint.hcl
level=debug msg="File parsed" path=prometheus-rules.yml rules=1
level=debug msg="Starting query workers" name=dev uri=https://xx workers=16
level=debug msg="Found alerting rule" alert=ProbeFail lines=6-10 path=prometheus-rules.yml
level=debug msg="Configured checks for rule" enabled=["alerts/count(dev)"] path=prometheus-rules.yml rule=ProbeFail
level=debug msg="Scheduling prometheus range query" lookback=1h query="probe_success == 0" slice=1h step=1m uri=https://xx uri=
level=debug msg="Cache miss" key=10041514857049195995 query="probe_success == 0" uri=
level=debug msg="Cache miss" key=6848501065476146297 query="probe_success == 0" uri=
level=debug msg="Running prometheus range query slice" end=2023-02-06T16:59:59+08:00 query="probe_success == 0" range=59m59s start=2023-02-06T16:00:00+08:00 step=1m
level=debug msg="Running prometheus range query slice" end=2023-02-06T17:18:37+08:00 query="probe_success == 0" range=18m37s160ms start=2023-02-06T17:00:00+08:00 step=1m 
level=debug msg="Query completed" duration=98ms endpoint=/api/v1/query_range query="probe_success == 0" uri=https://xx
level=debug msg="Query completed" duration=141ms endpoint=/api/v1/query_range query="probe_success == 0" uri=https://xx
level=debug msg="Parsed range response" query="probe_success == 0" samples=3 uri=https://xx
level=debug msg="Scheduling prometheus range query" lookback=1h query=count(up) slice=1h step=1m uri=https://xx
level=debug msg="Cache miss" key=13850570307350459569 query=count(up) uri=https://xx
level=debug msg="Running prometheus range query slice" end=2023-02-06T16:59:59+08:00 query=count(up) range=59m59s start=2023-02-06T16:00:00+08:00 step=1m uri=https://xx
level=debug msg="Cache miss" key=7578094931369544515 query=count(up) uri=https://xx
level=debug msg="Running prometheus range query slice" end=2023-02-06T17:18:37+08:00 query=count(up) range=18m37s313ms start=2023-02-06T17:00:00+08:00 step=1m uri=https://xx
level=debug msg="Query completed" duration=80ms endpoint=/api/v1/query_range query=count(up) uri=https://xx
level=debug msg="Query completed" duration=99ms endpoint=/api/v1/query_range query=count(up) uri=https://xx
level=debug msg="Parsed range response" query=count(up) samples=1 uri=https://xx
level=debug msg="Stopping query workers" name=dev uri=https://xx

**Comment by AlbusLumos** [comment]
solved this by set --min-severity to info

**Comment by prymitive** [comment]
#523 will log if there are problems hidden due to `--min-severity` filter
