### ISSUE TITLE
Way change status code for warnings

### ISSUE THREAD

**Issue by simPod** [cloudflare/pint#525]
I'd like to use Pint in CI. Pint reports warnings. But returns exit code 0 so my CI does not fail on warnings. Would it make sense to make it at least configurable to report something else than 0?

**Comment by prymitive** [comment]
Added `pint ci --fail-on` flag. It defaults to `--fail-on=bug` but passing `--fail-on=warning` will exit with 0 on any warning.

**Comment by simPod** [comment]
Thanks! Will validate when new release is out.

**Comment by simPod** [comment]
@prymitive can we have the option for `lint` as well?

`ci` does not really work for me since I use monorepo and having pint in subdirectoried is not really supported. I'd rather specify paths to check then having them inferred from git.
