### ISSUE TITLE
Add `fail-on` flag to `lint`

### ISSUE THREAD

**Issue by simPod** [cloudflare/pint#570]
Can we have the `fail-on` flag for `lint` as well (same as for `ci`)?

`ci` does not really work for me since I use monorepo and having pint in subdirectory is not supported. I'd rather specify paths to check using `lint` then having them inferred from git.

**Comment by prymitive** [comment]
There's already `--min-severity` but that's more for controlling what to show, rather than what to fail on, so I think `--fail-on` would still make sense in `lint`.

**Comment by simPod** [comment]
Yes, the point is to get non-zero exit code when there are warnings.
