### ISSUE TITLE
unknown rule type: alerting|recording

### ISSUE THREAD

**Issue by wbollock** [cloudflare/pint#601]
I'm getting an error setting a rule to match both alerting and recording with a pipe OR between them, although this behavior seems permitted in the documentation. On version 0.43.1.

Error:
```console
| level=fatal msg="Execution completed with error(s)" error="failed to load config file \"./.pint.hcl\": unknown rule type: alerting|recording"
```

Rule:
```hcl
rule {
  match {
    kind = "alerting|recording"
  }

  reject "datacenter" {
    label_keys = true
  }

}
```

**Comment by prymitive** [comment]
`kind = "alerting|recording"`

it's either `kind = "alerting"` or `kind = "recording"`, `"alerting|recording"` is not a valid value.
Don't put any `kind` if you want both.

**Comment by wbollock** [comment]
Ah okay, that makes sense thank you. I got the idea from here: https://github.com/cloudflare/pint/blob/5ece79f37d51c44def20104f1e93dc8e5d93b6be/docs/configuration.md?plain=1#L326-L338
