### ISSUE TITLE
output lint result as a machine friendly format

### ISSUE THREAD

**Issue by LeoQuote** [cloudflare/pint#606]
We are considering using it in jenkins pipeline rather than github actions, if there's a `-o` options to output lint result as those format, it would be very useful.

* checkstyle
* json
* golint , each line for each error

**Comment by thejuan** [comment]
Keen to see JSON as well, are you accepting PRs?

**Comment by nogweii** [comment]
A golint or similar style would be appreciated to be able to have `pint`'s errors appear in code reviews via [reviewdog](https://github.com/reviewdog/reviewdog).
