### ISSUE TITLE
Expand `ci` comment to state rule errors below a fold

### ISSUE THREAD

**Issue by wbollock** [cloudflare/pint#608]
Instead of Pint just reporting things are wrong with the `ci` mode, it would be great if Pint would also tell the user the exact linting problem, maybe below a fold. e.g:

### This pull request was validated by [pint](https://github.com/cloudflare/pint).
:heavy_exclamation_mark:	Problems found.
| Severity | Number of problems |
| --- | --- |
| Fatal | 6 |
| Information | 17 |
<details><summary>Stats</summary>
<p>

| Stat | Value |
| --- | --- |
| Version | 0.43.1 |
| Number of rules checked | 15 |
| Number of problems found | 23 |
| Number of offline checks | 105 |
| Number of online checks | 66 |
| Checks duration | 8s124ms |

</p>
</details>

<details><summary>Problems</summary>
<p>
<code>
infra/datacenter/dc1/rules.yaml:19 Information: prometheus "infra" at https://prometheus1.com/prometheus/prometheus/ didn't have any series for "volume_operation_duration_seconds:avg_over_time1h" metric in the last 1w but found recording rule that generates it, skipping further checks (promql/series)
19|  - expr: "stddev_over_time(volume_operation_duration_seconds:avg_over_time1h[1w])"

infra/services/alertmanager.yaml:15-16 Bug: component label is required (rule/label)
 15 |     labels:
 16 |       severity: "critical"
</code>
</p>
</details>

Thoughts? Could be only enabled as a `ci{}` config option too.

**Comment by prymitive** [comment]
Added in #644
