### ISSUE TITLE
add include and exclude option in pint lint

### ISSUE THREAD

**Issue by LeoQuote** [cloudflare/pint#631]
we are using pint to scan a folder ,but this folder may contains  README.md ,which will lead to 
```
values/blackbox-exporter/README.md:3 Fatal: found character that cannot start any token (yaml/parse)
```

a `exclude` or `include` parameter in pint lint command or parser config will help do the work.

**Comment by fourhundredfour** [comment]
You can pass a regex/glob to the lint command.
e.g. `pint lint **/*.yaml`

**Comment by jburnitz** [comment]
I believe [this PR](https://github.com/cloudflare/pint/pull/952) solves this issue

**Comment by jburnitz** [comment]
@LeoQuote is the above what you were thinking?

**Comment by LeoQuote** [comment]
yes exactly
