### ISSUE TITLE
Pull Request comments failing when problem reported on unmodified line

### ISSUE THREAD

**Issue by wbh1** [cloudflare/pint#645]
Hello again 👋🏻  Thank you for looking at https://github.com/cloudflare/pint/issues/640 so quickly!

I tested the new release and now we're seeing a new bug:
```console
level=fatal msg="Execution completed with error(s)" error="submitting reports: POST https://<REDACTED>/api/v3/repos/ops/prometheus_rules/pulls/244/comments: 422 Validation Failed [{Resource:PullRequestReviewComment Field:pull_request_review_thread.line Code:custom Message:pull_request_review_thread.line required and an integer greater than zero} {Resource:PullRequestReviewComment Field:pull_request_review_thread.diff_hunk Code:missing_field Message:}]"
```

It's coming from the same message as the prior issue:
```console
level=debug msg="Creating review comment" body="[promql/series](https://cloudflare.github.io/pint/checks/promql/series.html): Problem reported on unmodified line 10, annotation moved here: metric \"http_requests_total\" with label {code=~\"5..\"} is only sometimes present on prometheus \"infra_dallas\" at https://<REDACTED>.linode.com/prometheus/prometheus/ with average life span of 12h8m34s" commit=048da4b0c0973877a3f39e463c517cab984d8f65
```

Maybe worth noting that there's several log lines about ignoring issues on lines 10-15, but I guess the `promql/series` check makes it through because it's fatal severity. Presumably, pint's not finding any modified lines to attach the comment to and `moveReportedLine` is returning `-1` as the `reported` value to attach the comment to.

I'll be submitting a PR with a proposed fix that we have working.

**Comment by prymitive** [comment]
Should be fixed via #648 648
