### ISSUE TITLE
Hanging on large input files (are lots of smaller files prefered?)

### ISSUE THREAD

**Issue by thejuan** [cloudflare/pint#661]
We have a ~3Mb (2000+ rules) file I am trying out with Pint in offline mode.
It maxs the CPU's (8 physical) and doesn't seem to run (40mins+)
No debug output after config loading (if specified)

Should files this size be  a problem? Is it designed to be run against lots of little files instead?

This is running in WSL.

**Comment by prymitive** [comment]
Running it with debug logging (`pint -l debug`) should tell you what it's doing.
If that doesn't help then try running `pint -l debug watch <dir>` and then collect a pprof profile with `go tool proof http://localhost:8080/debug/pprof/profile?seconds=5`

**Comment by thejuan** [comment]
Thanks, I used `yq` to split out the files. It runs in seconds, so we'll just avoid large single files.

**Comment by prymitive** [comment]
When I generate a 2.7MB rule file with 4000 simple alerts and run `pint --offline lint test.yaml` it finishes in under 2 minutes.
If you run online checks against Prometheus servers then these will take a lot longer depending on how fast queries are. If that's the case you might want to:
- modify `concurrency` & `rateLimit` options - https://cloudflare.github.io/pint/configuration.html#prometheus-servers
- disable some slow checks like `alerts/count`
