### ISSUE TITLE
invalid key on valid prometheus `keep_firing_for` property

### ISSUE THREAD

**Issue by tl-eirik-albrigtsen** [cloudflare/pint#712]
The `keep_firing_for` field was added to prometheus alerts in https://github.com/prometheus/prometheus/pull/11827 which landed in [2.42.0](https://github.com/prometheus/prometheus/releases/tag/v2.42.0) and is also supported in prometheus-operator in [prometheusrules](https://github.com/prometheus-operator/prometheus-operator/blob/74505c38464bd93b4054eb45031cb463cca64fde/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml#L97-L103).

when running `pint lint prod/` (say) on a folder with prometheusrules containing the property a `yaml/parse` error triggers on all alerts with this key:

```
prod/thanos-alerts.yaml:294 Fatal: invalid key(s) found: keep_firing_for (yaml/parse)
 294 |       keep_firing_for: 5m
```

`pint version` at `0.45.0 (revision: Homebrew)`

am running a relaxed "yaml/parse" setup with `.pint.hcl` containing:

```hcl
parser {
  relaxed = [ "(.*)", "yaml/parse" ]
}
```

to support prometheusrule usage but this does not seem to suppress the error. not sure if there are other ways to ignore this error explicitly.

at any rate it would be nice to have this property supported!

**Comment by prymitive** [comment]
Fixed in #713 713
