### ISSUE TITLE
Regexp mode modifier not detected

### ISSUE THREAD

**Issue by vaegt** [cloudflare/pint#782]
Hi there 👋 

When using pint on some existing rules we had an issue with the `promql/regexp` checking.
```
/Bug: Unnecessary regexp match on static string `some_label=~"(?i)somename"`, use `some_label="(?i)somename"` instead. (promql/regexp)
 25 |         expr: some:latency_seconds_avg:1m{some_label=~"(?i)somename"} * 1000 > 500
```
So when using the regex mode modifier `(?i)` to match case insensitive, the check detects a static string.

**Comment by prymitive** [comment]
Thanks, will be fixed in the next minor release
