### ISSUE TITLE
GitHub reporter returning invalid request errors 

### ISSUE THREAD

**Issue by gbprz** [cloudflare/pint#935]
## Summary

Our team started noticing new Pint errors when checking our GitHub Actions workflow logs. I created a test repo to generate an example error: 

`
level=ERROR msg="Execution completed with error(s)" err="submitting reports: POST https://api.github.com/repos/gbprz/pint-test/pulls/2/comments: 422 Invalid request.\n\nNo subschema in \"oneOf\" matched.\n\"path\", \"position\" weren't supplied.\n\"in_reply_to\" wasn't supplied.\n\"line\", \"path\" weren't supplied.\n\"path\", \"subject_type\" weren't supplied. []"
`

Pint seems to be working well since the logs show failing checks and PR comments appear, but this error in the logs has been causing some confusion.

## Reproducing the error

I put together a quick repo and PR to reproduce this:

- PR: https://github.com/gbprz/pint-test/pull/2
- Logs: https://github.com/gbprz/pint-test/actions/runs/8443552421/job/23127410396?pr=2#step:4:79 

Everything is okay when the checks pass, but the `422 invalid` request errors were throwing us off.

Looking more closely at the logs, I see this debug message just before the error:
`
level=DEBUG msg="Creating review comment" body="This pint run would create 1 comment(s), which is more than 0 limit configured for pint.\n1 comments were skipped and won't be visibile on this PR." commit=73bc728e6826392d0a9b69ffcf98c6d792f4bee9
`

## New `maxComments` error message and PR comment

I looked more closely and noticed the recent changes to add a `maxComments` config. 

Maybe we're running into issues with the new error message that's also supposed to be sent as a PR comment? https://github.com/cloudflare/pint/blob/main/internal/reporter/github.go#L329-L336 

We didn't have the `maxComments` flag set in our Pint config previously, I also noticed it's supposed to default to `50`: https://github.com/cloudflare/pint/releases/tag/v0.57.2

**Comment by gbprz** [comment]
I ran another experiment, it looks like explicitly setting `maxComments = 50` instead of depending on the default fixed this. 

I think the default might unexpectedly be `0` instead of `50`? 

Here's my test PR: https://github.com/gbprz/pint-test/pull/3

Logs with the failing Pint check but no `422` error: https://github.com/gbprz/pint-test/actions/runs/8443927252/job/23128506566#step:4:72

**Comment by gbprz** [comment]
The main issue on our team's side might be that we never set a repository config: https://cloudflare.github.io/pint/configuration.html#repository 

I think this means the default for `maxComments` is never set:
https://github.com/cloudflare/pint/blob/main/internal/config/config.go#L273-L283

Even though we see PR comments without the repo config, this might be a case of us configuring the tool incorrectly for CI.

**Comment by prymitive** [comment]
Should be fixed in v0.57.3
